# baseurl: /curtis-garage-doors
exclude: ['README.md']
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://uptowndoors.ca"
gems:
  - jekyll-sitemap

permalink: pretty
markdown: kramdown

exclude:
  - s3_website.yml
